### ISSUE TITLE
Dark Mode and Macbook with dark theme

### ISSUE THREAD

**Issue by teipeps** [BirjuVachhani/adaptive_theme#18] opened 2021-04-09 11:15 UTC
**Describe the bug**
When you set dark theme on macbook and run the app on chrome (WEB), the library return always dark theme

**To Reproduce**
Run the app on a macbook with dark theme set.
Try ti switch to light theme. It doesn't work.

If macbook theme is on light or automatic non problem occur.

Library version 2.1.0
Flutter version 2.0.4
MacOS Big Sure 11.2.3

BR

**Comment by BirjuVachhani** [comment] 2021-04-09 12:13
@teipeps I was able to reproduce this. It seems that due to some recent changes this is happening. Old versions seems to be working fine. I'll fix this as soon as possible.

**Comment by teipeps** [comment] 2021-04-09 12:43
@BirjuVachhani TNKS !!!!!

**Comment by BirjuVachhani** [comment] 2021-04-09 15:09
@teipeps Fixed in `v2.1.1`

**Closed by BirjuVachhani** 2021-04-09 15:09 UTC
Labels: bug
