### ISSUE TITLE
App theme doesn't update if app is started while the system was in dark mode

### ISSUE THREAD

**Issue by erwangse** [BirjuVachhani/adaptive_theme#32] opened 2022-02-15 09:29 UTC
**Describe the bug**
App theme doesn't update if the app is started while the system was in dark mode.
I have only tested this on an Android 11 phone, the Oneplus Nord.

**The code**
```dart
class MyApp extends StatelessWidget
{
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context)
  {
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersive);

    // Auto-reset immersive mode on UI change after 1 sec
    SystemChrome.setSystemUIChangeCallback
    (
      (systemOverlaysAreVisible) => Future.delayed
      (
        const Duration(seconds: 2),
        ()
        {
          SystemChrome.restoreSystemUIOverlays();
        }
      )
    );

    return AdaptiveTheme
    (
      light: AppTheme.lightTheme, // Custom Material theme overrides
      dark: AppTheme.darkTheme,
      initial: AdaptiveThemeMode.system,
      builder: (theme, darkTheme)
      {
        return MaterialApp
        (
          supportedLocales: const
          [
            Locale('en'),
            Locale('fr'), // Fallback lang
          ],

          localizationsDelegates:
          [
            FlutterI18nDelegate
              (
              translationLoader: FileTranslationLoader
                (
                  basePath: 'assets/i18n',
                  fallbackFile: 'fr'
              ),
              missingTranslationHandler: (key, locale)
              {
                if (kDebugMode)
                {
                  print("i18n --- Missing Key: $key, languageCode: ${locale?.languageCode}");
                }
              },
            ),
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate
          ],

          debugShowCheckedModeBanner: true,
          title: 'My App',
          initialRoute: '/',
          routes: AppRoutes.appRoutes,
          theme: theme,
          darkTheme: darkTheme,
        );
      }
    );
  }
}
```

**Environment**
 - OS: Android 11
 - adaptive_theme: 2.3.0

**Additional info**
- I've noticed that, if I change the system from light/dark mode when the theme isn't updating, I don't even get a log message in my `flutter run` session. I do get logs notifying a theme change when I start the app when the system is in light mode, however.

- So far I don't know if the issue is with my code or your package, I'll be very grateful if you could help me on this.

- Note that the issue appears regardless if the app is in release or debug mode.

**Comment by Arfmann21** [comment] 2022-03-19 15:36
Same here, anyone got a fix?

**Comment by BirjuVachhani** [comment] 2022-04-03 19:28
I have release a fix for system theme change not being detected. Please try `v2.3.1` and if this issue is fixed.

**Comment by gnassro** [comment] 2022-04-04 11:38
> I have release a fix for system theme change not being detected. Please try `v2.3.1` and if this issue is fixed.

same issue, app theme doesn't update if app is started while the system was in dark mode. only work when the app is started while system not in dark mode

**Comment by BirjuVachhani** [comment] 2022-04-04 12:45
That's strange. I also do have **Oneplus Nord CE** with **Android 11** and when I start my app while system is in dart mode, it works fine for me.

Checkout [this part of the docs](https://github.com/BirjuVachhani/adaptive_theme#get-thememode-at-app-start) where the mode is retrieved from storage before loading the app. Maybe this can fix your issue but I am not sure.

To help me reproduce this, could you please create an example app with the same issue and provide exact steps to reproduce? (like does it happen on first run or second run?)

**Comment by gnassro** [comment] 2022-04-05 18:33
> That's strange. I also do have **Oneplus Nord CE** with **Android 11** and when I start my app while system is in dart mode, it works fine for me.
> 
> Checkout [this part of the docs](https://github.com/BirjuVachhani/adaptive_theme#get-thememode-at-app-start) where the mode is retrieved from storage before loading the app. Maybe this can fix your issue but I am not sure.
> 
> To help me reproduce this, could you please create an example app with the same issue and provide exact steps to reproduce? (like does it happen on first run or second run?) At least post the exact code here.

yes you are right, i think there is something wrong in my project, because when i create new project and using the same  `ThemeData` that i used in my project, it worked fine

**Comment by BirjuVachhani** [comment] 2022-04-06 05:38
@gnassro I thought so. Please check your configuration and make sure you're not changing theme explicitly from somewhere.

**Comment by BirjuVachhani** [comment] 2022-04-06 05:39
@erwangse Does the latest release work for you?

**Comment by gnassro** [comment] 2022-04-06 08:22
> @gnassro I thought so. Please check your configuration and make sure you're not changing theme explicitly from somewhere.

I discovered that the problem because of using this package https://pub.dev/packages/preload_page_view. when i replace it with the default Widget, it work fine

**Comment by BirjuVachhani** [comment] 2022-04-06 13:29
@gnassro Ah! I think that package caches widgets so those widgets are not updated when the theme is changed. Although this is not a solution, can you try setting the `preloadPagesCount` to `0` (if allowed) just to check if that works as widgets shouldn't be cached in that case.

**Comment by BirjuVachhani** [comment] 2022-04-07 11:11
Closing this issue as it seems to be fixed. Feel free to reopen if it does work for some reason.

**Closed by BirjuVachhani** 2022-04-07 11:11 UTC

**Comment by erwangse** [comment] 2022-04-13 13:44
Hi there, just wanted to make a quick follow-up and add a bit of context to this !
I'm the (currently) sole developer of a flutter app in my company, sorry I didn't respond in time.
As for your first concern, I do cache theme changes in Hive & restore them on startup.
And as for your second, the new release seems to work just fine ! Thanks ! :+1:
